FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /app

COPY . ./
# copy csproj and restore as distinct layers
#COPY *.csproj ./
RUN ls
RUN dotnet restore


# copy everything else and build app
COPY . ./
WORKDIR /app/RabbitMqConsumer
RUN dotnet publish -c Release -o /app/out


FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
WORKDIR /app
COPY --from=build /app/out .

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet", "RabbitMqConsumer.dll"]